<?php

namespace Shop\BookshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderModelRepository extends EntityRepository
{
    public function getOrderByUser($id)
    {
        $qb = $this->createQueryBuilder('o')
                        ->select('o')
                        ->where('o.user = :id')->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
