<?php

namespace Shop\BookshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShippingMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingMethodRepository extends EntityRepository
{

    public function getShippingMethodsWithPrice()
    {
        $qb = $this->createQueryBuilder('s')
                ->select('s.label', 's.price');
        return $qb;
    }

}
