parameters:
#    shop_bookshop.example.class: Shop\BookshopBundle\Example
    finder.class: Symfony\Component\Finder\Finder
    helper.class: Shop\BookshopBundle\Helper\Helper
    request.class: Symfony\Component\HttpFoundation\Request

services:
#    shop_bookshop.example:
#        class: %shop_bookshop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    finder:
        class: "%finder.class%"
    helper:
        class: "%helper.class%"
    request:
        class: "%request.class%"
    user.registration.form.type:
        class: Shop\BookshopBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_registration }
